"""Utilidad para convertir Markdown a formato Jira."""

import re


def markdown_to_jira(markdown_text: str) -> str:
    """
    Convierte texto en formato Markdown a formato Jira markup.
    
    Args:
        markdown_text: Texto en formato Markdown
        
    Returns:
        Texto en formato Jira markup
    """
    text = markdown_text
    
    # Headers: ## Title -> h2. Title
    text = re.sub(r'^### (.+)$', r'h3. \1', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'h2. \1', text, flags=re.MULTILINE)
    text = re.sub(r'^# (.+)$', r'h1. \1', text, flags=re.MULTILINE)
    
    # Bold: **text** -> *text*
    text = re.sub(r'\*\*(.+?)\*\*', r'*\1*', text)
    
    # Italic: *text* -> _text_
    text = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'_\1_', text)
    
    # Code blocks: ```language\ncode\n``` -> {code:language}code{code}
    text = re.sub(r'```(\w+)?\n(.*?)\n```', lambda m: f"{{code:{m.group(1) or 'none'}}}\n{m.group(2)}\n{{code}}", text, flags=re.DOTALL)
    
    # Inline code: `code` -> {{code}}
    text = re.sub(r'`(.+?)`', r'{{\1}}', text)
    
    # Unordered lists: - item -> * item
    text = re.sub(r'^- ', r'* ', text, flags=re.MULTILINE)
    
    # Checkboxes: - [ ] -> * [ ]
    text = re.sub(r'^\* \[ \]', r'* [ ]', text, flags=re.MULTILINE)
    text = re.sub(r'^\* \[x\]', r'* [x]', text, flags=re.MULTILINE)
    
    # Ordered lists are the same: 1. item
    
    # Links: [text](url) -> [text|url]
    text = re.sub(r'\[(.+?)\]\((.+?)\)', r'[\1|\2]', text)
    
    # Blockquotes: > text -> {quote}text{quote}
    # Find consecutive lines starting with >
    lines = text.split('\n')
    result_lines = []
    in_quote = False
    
    for line in lines:
        if line.strip().startswith('>'):
            if not in_quote:
                result_lines.append('{quote}')
                in_quote = True
            result_lines.append(line.lstrip('>').strip())
        else:
            if in_quote:
                result_lines.append('{quote}')
                in_quote = False
            result_lines.append(line)
    
    if in_quote:
        result_lines.append('{quote}')
    
    text = '\n'.join(result_lines)
    
    # Emojis - keep as is, Jira supports them
    
    return text


def prepare_analysis_for_jira(analysis_text: str, story_key: str) -> str:
    """
    Prepara el análisis para ser publicado en Jira.
    Agrega un header y convierte el formato.
    
    Args:
        analysis_text: Texto del análisis en Markdown
        story_key: Clave de la historia
        
    Returns:
        Texto formateado para Jira
    """
    header = f"h2. 🤖 AI Analysis for {story_key}\n\n"
    header += "_This analysis was generated by Story Prompt Analyzer_\n\n"
    header += "----\n\n"
    
    jira_text = markdown_to_jira(analysis_text)
    
    return header + jira_text
